# Generated by Django 5.0.1 on 2024-02-04 12:43

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('max_value_x', models.PositiveIntegerField(verbose_name='Максимальное значение по оси x')),
                ('max_value_y', models.PositiveIntegerField(verbose_name='Максимальное значение по оси y')),
                ('json_key_name', models.CharField(max_length=250, verbose_name='Название ключа в поле json')),
                ('json_value_name', models.CharField(max_length=250, verbose_name='Название значения в поле json')),
            ],
            options={
                'verbose_name': 'Типы характеристик',
                'verbose_name_plural': 'Типы характеристик',
                'db_table': 'characteristic_types',
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Скважины',
                'verbose_name_plural': 'Скважины',
                'db_table': 'wells',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', jsonfield.fields.JSONField(verbose_name='Значение')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('characteristic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chars_catalog.characteristictype', verbose_name='Вид характеристики')),
            ],
            options={
                'verbose_name': 'Характеристики',
                'verbose_name_plural': 'Характеристики',
                'db_table': 'characteristics',
            },
        ),
        migrations.CreateModel(
            name='WellCharacteristicBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chars_catalog.characteristic')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chars_catalog.well')),
            ],
            options={
                'verbose_name': 'Характеристики скважин',
                'verbose_name_plural': 'Характеристики скважин',
                'db_table': 'wells_characteristics',
            },
        ),
    ]
