# Generated by Django 5.0.1 on 2024-02-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chars_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristictype',
            name='permitted_groups',
            field=models.ManyToManyField(related_name='allowed_char_types', to='auth.group', verbose_name='Разрешенные группы'),
        ),
    ]
