# Generated by Django 5.0.1 on 2024-02-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chars_catalog', '0002_characteristictype_permitted_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristictype',
            name='permitted_groups',
        ),
    ]
